name: GuestModePlugin
version: 1.0
main: org.example.guestmode.GuestModePlugin
api-version: 1.21
commands:
  guestmode:
    description: Включить/выключить гостевой режим
    usage: /<command>
permissions:
  guestmode.command:
    description: Разрешение на использование команды /guestmode
    default: op
